### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by zgtibu** [marcosvrs/wtf#1]
It is difficult to understand the options in it.

**Comment by marcosvrs** [comment]
It isn't internationalized yet. I will work on this in the future.

**Comment by marcosvrs** [comment]
The new version 3.2.1 containing the i18n to English has been sent to the Chrome Web Store and should be available soon.
Enjoy and consider reviewing our extension on the Web Store: https://chrome.google.com/webstore/detail/whatsapp-toolbox-features/fockmbfncdacmjbmieenodfeblmneaii
:)
