### ISSUE TITLE
Chrome out of memory/ Web page crashed.

### ISSUE THREAD

**Issue by chavanshashank** [marcosvrs/WTF#11]
Issue: Chrome Whatsapp web page is crashing with out-of-memory/error code:5 issue. I am trying to use this for my wife's clinic purpose.

Reproduce: 
1. Set a message and one image attachment 
2. Have a 6 seconds interval.
3. Set some prefix country code from the dropdown.
4. Add around 100 numbers to a list and start sending.

Chrome current WhatsApp tab will crash after sending a few messages, I have replicated this on Macbook Pro with 16GB RAM and Windows laptop as well.

I have experience working only in the JVM ecosystem, but let me know if I can contribute.

**Comment by marcosvrs** [comment]
Haven't gone that far with my tests, thank you for sharing it!

I will research for a better memory handling for such a high usage and let you know if I can find a better solution! Will keep this issue open until then :)
Of course, if you have time and wish to contribute, feel free to open a pull request, so we can work on it together.

So far, the best you can do is to split the numbers into small chunks (I bet you are already doing it ;) )

**Comment by chavanshashank** [comment]
Thank you!
Sure will look forward to the update.

**Comment by rohankm** [comment]
facing the same issue

**Comment by xadnane** [comment]
Any solution for this problem?

**Comment by ChetanMotghare** [comment]
Facing the same issue, it just sending first message message and then it stuck

**Comment by marcosvrs** [comment]
Tested the new version v3.3.1 with one thousand numbers and the memory kept low.
The solution to use the indexedDB as caching worked! Please let me know if there are still issues.
