### ISSUE TITLE
WhatsApp web Message UI Blank After Installing Chrome Extension (v3.3.1)

### ISSUE THREAD

**Issue by ChetanMotghare** [marcosvrs/WTF#23]
**Issue Description:**
After installing the Chrome extension version 3.3.1 ( 3.3.0), I encountered a critical issue with the WhatsApp web interface. The issue causes the WhatsApp message user interface to go completely blank, rendering it unusable.

**Steps to Reproduce:**

1. Install the Chrome extension version 3.3.1.
2. Open WhatsApp Web in your browser (tested on both Chrome and Brave).
3. Observe that the WhatsApp message UI becomes blank, with no chat threads or messages visible.

**Expected Behavior:**
After installing the extension, the WhatsApp web interface should function normally, 

**Actual Behavior:**
The WhatsApp web interface becomes entirely blank, preventing users from accessing their chat threads.

https://recordit.co/puUoHqNDJc

**Comment by marcosvrs** [comment]
Seems a bug from our library: https://github.com/wppconnect-team/wa-js/issues/1322
I will keep watching it and see if there is any update.
Seems to be related only to the WA business.
