### ISSUE TITLE
[FEATURE] recive messages

### ISSUE THREAD

**Issue by jpliraa** [marcosvrs/WTF#48]
Can recive messges with the chat.new_message event?

**Comment by marcosvrs** [comment]
Hi @jpliraa,

This app was supposed to only send messages in a bulk.

But, which is your use case to receive messages and what to do with them?

**Comment by marcosvrs** [comment]
As I mentioned, this app is only supposed to send messages.
A complete CRM solution might come in the future, but not for this app.
