### ISSUE TITLE
[BUG] unable to see any options

### ISSUE THREAD

**Issue by 7odaifa-ab** [marcosvrs/WTF#74]
## Describe the bug

cannot add message or even see any options after pressing the option button 

## To Reproduce

1. Click on '.WTF'
2. Click on '.option '
3. See error

## Expected behavior

able to add message and attachments 

## Screenshots

![image](https://github.com/user-attachments/assets/c42f77b6-00e2-4df0-8f0f-55244e8008e7)

## Environment (please complete the following information):

- OS: [windows 10 and 11]
- Browser [chrome]

**Comment by marcosvrs** [comment]
Just pushed a fix.
Thanks for raising the issue!

**Comment by 7odaifa-ab** [comment]
either soo it seems WhatsApp has blocked it, as you cannot open whatsapp web if the extension is enabled
